services:
  mysql:
    image: mysql:lts
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sports_day
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    platform: linux/amd64
    restart: always
    depends_on:
      - mysql
    ports:
      - "3003:80"
    environment:
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PMA_ABSOLUTE_URI=http://localhost:3003
  api:
    image: ghcr.io/sports-day/sportsdayapiprocon:main
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_DB=sports_day
      - DATABASE_HOST=mysql
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - JWT_SECRET=ze2ykHlVRRnf0at+QyMTUYnye3o0OzddxraVNg6Hpw0=
      - JWT_ISSUER=localhost
      - JWT_EXPIRE_MINUTE=7200
      - JWT_REALMS=localhost
      - COOKIE_SECURE=false
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  panel:
    image: ghcr.io/sports-day/sports-day-panel-procon:main
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - NEXT_PUBLIC_API_URL=http://localhost:8080/v1
      - NEXT_PUBLIC_API_INTERNAL_URL=http://host.docker.internal:8080/v1
    ports:
      - "3000:3000"
    depends_on:
      - api
  admin:
    image: ghcr.io/sports-day/sports-day-admin-procon:main
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - NEXT_PUBLIC_API_URL=http://localhost:8080/v1
      - NEXT_PUBLIC_API_INTERNAL_URL=http://host.docker.internal:8080/v1
    ports:
      - "3001:3000"
    depends_on:
      - api
  form:
    image: ghcr.io/sports-day/sports-day-form-procon:main
    platform: linux/amd64
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - NEXT_PUBLIC_API_URL=http://localhost:8080/v1
      - NEXT_PUBLIC_API_INTERNAL_URL=http://host.docker.internal:8080/v1
    ports:
      - "3002:3000"
    depends_on:
      - api
